Ewm 207
broxus/ever_wallet_flutter_new pull request #409
Opened 2024-07-04 04:47 UTC by knightsforce

## Description

Use Elementary instead Cubit for WalletPrepareTransferPage

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [ ] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [X] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

2024-07-10 09:08 UTC, AndreyMolochko requested changes

2024-07-11 09:07 UTC, knightsforce commented on utils/elementary_generator/mwwmgen.dart
> +    var fileContent = await newFile.readAsString();
Это утилита для быстрой генерации файлов разработчиком.
Папка utils Лежит рядом с lib.

Если тут будет краш - то это ни на чем не отразится. Просто не создадутся файлы.
Если try..catch  поймает ошибку - также просто не создадутся файлы.

Могу обернуть. Но пользы немного.

2024-07-11 10:28 UTC, knightsforce commented on lib/feature/wallet/wallet_prepare_transfer/wallet_prepare_transfer_page/wallet_prepare_transfer_page_model.dart
> +    _currentWalletSubscription?.cancel();
Он вызывается выше в dispose.
Не добавлен в этот метод так как _contractSubscription?.cancel() и _closeBalanceSubs() вызываются в dispose, но дополнительно в разных местах.

2024-07-11 10:31 UTC, AndreyMolochko approved these changes

2024-07-11 10:35 UTC, merged